services:
  jobspring-db:
    image: postgres:16
    container_name: jobspring-db
    environment:
      POSTGRES_DB: jobspring
      POSTGRES_USER: jobspring
      POSTGRES_PASSWORD: jobspring123
    ports:
      - "5433:5432"
    volumes:
      - jobspring_data:/var/lib/postgresql/data

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: jobspring-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

volumes:
  jobspring_data:
  keycloak_data: