spring.application.name=job-spring-backend

server.port=8081
server.address=localhost

#config datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/job_spring_db
spring.datasource.username=jobspring
spring.datasource.password=jobspring@123

#config Spring Data JPA - Use Create-drop in dev
spring.jpa.hibernate.ddl-auto=create-drop

